-- MySQL Script generated by MySQL Workbench
-- Thu Nov 26 11:21:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(12) NULL,
  `password` VARCHAR(128) NULL,
  `occupation` VARCHAR(255) NULL,
  `location` VARCHAR(50) NULL,
  `created` TIMESTAMP NULL,
  `token` VARCHAR(128) NULL,
  `status` VARCHAR(10) NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`licenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`licenses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subcategory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subcategory_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_subcategory_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `thumbnail` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `created` TIMESTAMP NULL,
  `slug` VARCHAR(255) NULL,
  `users_id` INT NOT NULL,
  `licenses_id` INT NOT NULL,
  `subcategory_id` INT NOT NULL,
  `restrict_age` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_images_licenses1_idx` (`licenses_id` ASC) VISIBLE,
  INDEX `fk_images_subcategory1_idx` (`subcategory_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_images_licenses1`
    FOREIGN KEY (`licenses_id`)
    REFERENCES `mydb`.`licenses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_images_subcategory1`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `mydb`.`subcategory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`downloads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`downloads` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `images_id` INT NOT NULL,
  `ip_address` INT NULL,
  `created` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_downloads_images1_idx` (`images_id` ASC) VISIBLE,
  CONSTRAINT `fk_downloads_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `mydb`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL,
  `images_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `created` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_report_images1_idx` (`images_id` ASC) VISIBLE,
  INDEX `fk_report_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_report_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `mydb`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unread` TINYINT NULL,
  `title` VARCHAR(45) NULL,
  `report_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `created` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notification_report1_idx` (`report_id` ASC) VISIBLE,
  INDEX `fk_notification_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_notification_report1`
    FOREIGN KEY (`report_id`)
    REFERENCES `mydb`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`throttle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`throttle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `count` INT NULL,
  `last_login` TIMESTAMP NULL,
  `created` TIMESTAMP NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_throttle_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_throttle_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
